### ISSUE TITLE
[BUG] getLine on exclusive text mode terminal object only returns the text

### ISSUE THREAD

**Issue by Rainb0wSkeppy** [Phoenix-ComputerCraft/issues#12]
**Describe the bug**
Calling `getLine` on an exclusive text mode terminal object only returns the text

**To Reproduce**
1. Call `getLine` on an exclusive text mode terminal object

**Expected behavior**
It returns the text, fg and bg

**Information (please complete the following information):**
 - CraftOS-PC 2.8.1
 - ComputerCraft Version: 1.109.3
 - Phoenix Version: 0.0.5

**Comment by MCJack123** [comment]
Already had it fixed in my local copy, will be fixed in 0.0.6 :+1:
