### ISSUE TITLE
Phoenix can't be installed on CraftOS-PC

### ISSUE THREAD

**Issue by EmmaKnijn** [Phoenix-ComputerCraft/issues#4]
Phoenix checks for free space, but can't find any
![image](https://user-images.githubusercontent.com/64010592/187973267-1d560d0c-7406-401e-a351-3bdbb3e6fc60.png)
(This is on a fresh install of CraftOS-PC 2.7)

**Comment by EmmaKnijn** [comment]
Works fine on a fresh install of CCEmuX

**Comment by MCJack123** [comment]
This is an issue in CCPC v2.7 on Windows, and is fixed in v2.7.1. Please update to the latest version.

**Comment by Ocawesome101** [comment]
are you on windows?  v2.7 on windows has some weird bugs.

EDIT: oops, neglected to refresh

**Comment by EmmaKnijn** [comment]
Yep, was fixed with v2.7.1
