### ISSUE TITLE
Running `reboot` doesn't do anything

### ISSUE THREAD

**Issue by EmmaKnijn** [Phoenix-ComputerCraft/issues#5]
I know reboot isn't supposed to stop services cleanly but it doesn't do anything, not even uncleanly stop services

**Comment by MCJack123** [comment]
Make sure you're running `reboot` as root.

**Comment by EmmaKnijn** [comment]
Running `reboot` as root will make it reboot, but running it without root doesnt throw any errors
![image](https://user-images.githubusercontent.com/64010592/188070747-9b2eb21c-7f02-4a4f-9e3d-f115e7c5d068.png)

**Comment by MCJack123** [comment]
The reboot command is intended as more of a super tiny internal tool, and will likely be replaced later, so I won't be fixing this now.
