### ISSUE TITLE
Logging in with an unknown user still asks for a password 3 times

### ISSUE THREAD

**Issue by EmmaKnijn** [Phoenix-ComputerCraft/issues#6]
![image](https://user-images.githubusercontent.com/64010592/187975511-ba5ca0e9-fee8-4b41-a2cb-eb369e1a2d26.png)

**Comment by Ocawesome101** [comment]
my Arch install does this too, though it re-prompts for the username as well

**Comment by EmmaKnijn** [comment]
Indeed, I'd expect it to reprompt for the username
