### ISSUE TITLE
[BUG] Phoenix installer won't respond to term_resize events correctly

### ISSUE THREAD

**Issue by EmmaKnijn** [Phoenix-ComputerCraft/issues#8]
**Describe the bug**
The phoenix installer won't resize when the terminal size changes

**To Reproduce**
1. Open CraftOS-PC 2.7.1 in a small window
2. Start the phoenix installer
3. Make the CraftOS-PC window fullscreen
4. See bug

**Expected behavior**
I'd expect the text to resize or recenter as well

**Screenshots**
![image](https://user-images.githubusercontent.com/64010592/188070399-ab48bfd6-0f86-46e7-9c27-4f9b4c47734d.png)

**Information (please complete the following information):**
 - CraftOS-PC 2.7.1
 - ComputerCraft:Tweaked 0.100.9
 - Phoenix 0.0.1

**Comment by MCJack123** [comment]
The UI toolkit I'm using isn't really able to handle this properly without a major rewrite, and this issue's pretty minor itself, so I won't be fixing this.
